/* A focused working surface over the existing SitePlumb domain and editors.
 * Demo additions stay local. No cloud permission or delivery is implied. */
(function(){
 'use strict';
 const W=window.SitePlumbWorkspace={};
 const e=esc, js=v=>e(JSON.stringify(v)), copy=v=>JSON.parse(JSON.stringify(v));
 const role=()=>((state.session||{}).role||'builder');
 const project=id=>(state.projects||[]).find(p=>String(p.id)===String(id));
 const date=t=>t?new Date(t).toLocaleDateString(undefined,{month:'short',day:'numeric'}):'Not scheduled';
 const button=(label,action,primary=false)=>`<button class="ws-button${primary?' primary':''}" onclick="${action}">${e(label)}${primary?'<span aria-hidden="true">↗</span>':''}</button>`;
 const badge=(label,kind='neutral')=>`<span class="ws-badge ${kind}">${e(label)}</span>`;
 const empty=txt=>`<div class="ws-empty">${e(txt)}</div>`;
 const glance=p=>{if(!p)return '';const t=W.trades(p)[0];if(!t)return '';const so=packetSignoff(p,t);return '<div class="ws-glance"><div class="ws-eyebrow">Current instructions</div><div><span>Homeowner</span><b>'+ (so.homeowner?'Signed':'Pending')+'</b></div><div><span>Builder</span><b>'+(so.builder?'Signed':'Pending')+'</b></div><p>'+ (packetReady(p,t)?'Both approvals are complete.':'Installation stays on hold until both approve.')+'</p></div>';};
 W.trades=p=>[...new Set((p.subs||[]).map(s=>s.specialty))].filter(t=>tradeSelections(p,t).length);
 W.currentRecord=(p,t)=>(p.workspaceRecords||[]).find(r=>r.trade===t&&r.key===packetApprovalKey(p,t));
 W.next=(p,t)=>{
   const gaps=tradeSpecGaps(p,t),sign=packetSignoff(p,t),rec=W.currentRecord(p,t);
   if(gaps.length){const builder=gaps.some(s=>specStatus(s).requiredMissing.some(f=>f.who!=='homeowner'));return {label:builder?'Details needed':'Homeowner decision',who:builder?'Builder':'Homeowner',kind:'wait',detail:builder?'Complete the installation details.':'A finish answer is still needed.'};}
   if(!sign.homeowner)return {label:'Homeowner approval',who:'Homeowner',kind:'wait',detail:'The instructions are ready for homeowner review.'};
   if(!sign.builder)return {label:'Approval needed',who:'Builder',kind:'wait',detail:'The homeowner has signed. Review the current instructions.'};
   if(rec&&rec.verified)return {label:'Verified',who:'Complete',kind:'',detail:'Installation evidence has been reviewed.'};
   if(rec&&rec.installed)return {label:'Verify installation',who:'Builder',kind:'wait',detail:'The crew has recorded the finished work.'};
   if(rec&&rec.ack)return {label:'Ready for installation',who:'Crew',kind:'',detail:'The crew has acknowledged these instructions.'};
   return {label:'Instructions approved',who:'Crew',kind:'',detail:'Both approvals are complete. The crew can review its packet.'};
 };
 W.packet=(id,t)=>{const p=project(id);if(!p)return;if(role()==='client')openClientPacket(t);else if(role()==='subs')openSubPacket(p.id,t);else openPacketFor(p.id,t);};
 W.house=(id,view)=>{openSiteFromOverview(id);if(view)go(view);};
 W.nav=(p,who,active)=>'<div class="ws-nav" aria-label="House sections">'+(who==='client'?[['home','Your home'],['specs','Selections'],['progress','Updates'],['docs','Documents']].map(([v,n])=>`<button class="${active===v?'on':''}" onclick="clientGo('${v}')">${n}</button>`).join(''):[['log','House'],['selections','Selections'],['files','Files'],['subs','Crews']].map(([v,n])=>`<button onclick="SitePlumbWorkspace.house(${js(p.id)},'${v}')">${n}</button>`).join(''))+'</div>';
 W.activity=p=>{
   const entries=[];(p.selections||[]).forEach(s=>(s.revisionHistory||[]).forEach(r=>entries.push({at:r.at,text:(s.item||'Selection')+' instructions revised',by:r.by})));
   W.trades(p).forEach(t=>{const sign=packetSignoff(p,t);['homeowner','builder'].forEach(w=>{if(sign[w])entries.push({at:sign[w].at,text:(w==='homeowner'?'Homeowner':'Builder')+' approved '+specLabel(t).toLowerCase()+' instructions',by:sign[w].by});});});
   (p.workspaceRecords||[]).forEach(r=>['ack','installed','verified'].forEach(k=>{if(r[k])entries.push({at:r[k].at,text:specLabel(r.trade)+' '+({ack:'instructions acknowledged',installed:'installation recorded',verified:'installation verified'}[k]),by:r[k].by});}));
   return entries.sort((a,b)=>b.at-a.at).slice(0,4).map(x=>`<div class="ws-log"><i></i><div>${e(x.text)}<small>${e(x.by||'Project team')} · ${e(date(x.at))}</small></div>`).join('')||'<p class="ws-caption">Decisions and completed work will appear here as the house moves forward.</p>';
 };
 W.schedule=p=>{const b=(p.bookings||[]).filter(b=>b.status!=='declined'&&b.end>=dayStart(Date.now())).sort((a,b)=>a.start-b.start);return b.slice(0,3).map(b=>`<div class="ws-row"><div class="ws-row-main"><strong>${e(specLabel(b.trade)||b.subName)}</strong><small>${e(date(b.start))} – ${e(date(b.end))}</small></div>${badge(b.status==='confirmed'?'Scheduled':'Confirm dates',b.status==='confirmed'?'neutral':'wait')}</div>`).join('')||empty('No upcoming work has been scheduled.');};
 W.builderHome=()=>{
   const projs=visibleProjects(),all=projs.flatMap(p=>W.trades(p).map(t=>({p,t,n:W.next(p,t)}))),mine=all.filter(x=>x.n.who==='Builder'),lead=mine[0]||all.find(x=>x.n.who!=='Complete')||all[0],p=lead?lead.p:projs[0];
   const h=document.getElementById('ovToday');if(!h)return;
   const nextTitle=lead?(lead.n.who==='Complete'?'The recorded work is verified.':lead.n.who==='Builder'?(lead.n.label==='Verify installation'?'The work is ready for your review.':lead.n.label==='Approval needed'?'One review keeps the work moving.':'Give the crew the details they need.'):(lead.n.who==='Homeowner'?'A homeowner decision comes next.':'The crew has current instructions.')):'A clear view of every house.';
   h.innerHTML=`<div class="workspace"><div class="ws-heading"><div><div class="ws-eyebrow">Builder workspace</div><h1>Keep the build moving.</h1></div><div class="ws-date">${e(new Date().toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'}))}</div></div>
   <section class="ws-feature"><div><div class="ws-eyebrow">${lead?e(lead.p.street)+' · '+e(specLabel(lead.t)):'Your next step'}</div><h2>${nextTitle}</h2><p>${lead?e(lead.n.detail):'Decisions, instructions, and progress, together in one place.'}</p><div class="ws-actions">${lead?button(lead.n.label==='Verify installation'?'Review installation':'Review decision',`SitePlumbWorkspace.${lead.n.label==='Verify installation'?'workReview':'decision'}(${js(lead.p.id)},${js(lead.t)})`,true):button('Add your first house','openNewSite()',true)}${p?button('Open house',`SitePlumbWorkspace.house(${js(p.id)})`):''}</div></div>${glance(p)}</section>
   <div class="ws-grid"><div><section class="ws-section"><div class="ws-section-head"><h2>Decisions & follow-through</h2><small>${all.length} ${all.length===1?'packet':'packets'}</small></div><div class="ws-panel">${all.map((x,i)=>`<button class="ws-row" onclick="SitePlumbWorkspace.decision(${js(x.p.id)},${js(x.t)})"><span class="ws-row-num">${String(i+1).padStart(2,'0')}</span><span class="ws-row-main"><strong>${e(specLabel(x.t))} install packet</strong><small>${e(x.p.street||x.p.name)} · ${e(x.n.who==='Complete'?'Complete':'With '+x.n.who.toLowerCase())}</small></span>${badge(x.n.label,x.n.kind)}<span class="ws-arrow">›</span></button>`).join('')||empty('Add a house and its selections to prepare your first decision.')}</div></section>
   <section class="ws-section"><div class="ws-section-head"><h2>Your houses</h2>${button('Add a house','openNewSite()')}</div>${projs.map(p=>`<button class="ws-house" onclick="SitePlumbWorkspace.house(${js(p.id)})"><span class="ws-eyebrow">${e(p.city||'Custom home')}</span><h3>${e(p.street||p.name)}</h3><small>${e((p.buyers||[]).join(' & ')||'Your project team')}</small><span class="ws-house-footer"><span>${W.trades(p).filter(t=>!packetReady(p,t)).length} packets awaiting approval</span><span>Open house ↗</span></span></button>`).join('')}</section></div>
   <aside>${p?`<section class="ws-section"><div class="ws-section-head"><h2>Coming up on site</h2></div><div class="ws-panel">${W.schedule(p)}</div></section><section class="ws-section"><div class="ws-section-head"><h2>Recent progress</h2></div>${W.activity(p)}</section><div class="ws-panel ws-note"><div class="ws-eyebrow">The intent behind the work</div><h3>A home that works for them.</h3><p>${e((p.buildBrief||{}).priorities||'Keep the homeowner’s comfort, preferences, and priorities close to every decision.')}</p>${button('Open build brief',`SitePlumbWorkspace.brief(${js(p.id)})`)}</div>`:''}</aside></div><p class="ws-caption">${appMode()==='demo'?'Sample workspace · changes stay on this device · no messages are sent.':''}</p></div>`;
 };
 W.homeownerHome=p=>{
   const unanswered=(p.selections||[]).filter(s=>specStatus(s).homeownerPending.length),trades=W.trades(p),toSign=trades.find(t=>!tradeSpecGaps(p,t).length&&!packetSignoff(p,t).homeowner),lead=unanswered[0],next=(p.bookings||[]).find(b=>b.end>=Date.now());
   return `<div class="workspace">${W.nav(p,'client','home')}<div class="ws-heading"><div><div class="ws-eyebrow">Your home, taking shape</div><h1>${e(p.street||p.name)}</h1></div>${badge('Homeowner','neutral')}</div><section class="ws-feature"><div><div class="ws-eyebrow">${lead?'A decision for you':toSign?'Ready for your approval':'You’re up to date'}</div><h2>${lead?'Make it feel like your home.':toSign?'Your choices are ready to carry forward.':'Your choices are in good hands.'}</h2><p>${lead?e(lead.item)+' needs your '+e(specStatus(lead).homeownerPending.map(f=>f.label.toLowerCase()).join(' and '))+'. Your builder handles the technical details.':toSign?'Review the assembled instructions. Your approval applies to the details you see here.':'Your builder and crew can see where the work stands. We’ll show your next decision here.'}</p><div class="ws-actions">${lead?button('Choose your finish',"clientGo('specs')",true):toSign?button('Review instructions',`SitePlumbWorkspace.packet(${js(p.id)},${js(toSign)})`,true):button('View your selections',"clientGo('specs')",true)}</div></div>${glance(p)}</section>
   <div class="ws-grid"><div><section class="ws-section"><div class="ws-section-head"><h2>Your decisions</h2><small>${(p.selections||[]).length} selections</small></div><div class="ws-panel">${(p.selections||[]).map(s=>{const tr=selectionReviewTrades(p,s)[0],n=tr?W.next(p,tr):null;return `<button class="ws-row" onclick="clientGo('specs')"><span class="ws-row-main"><strong>${e(s.item)}</strong><small>${e(s.room||'Your house')}${s.spec&&s.spec.finish?' · '+e(s.spec.finish):''}</small></span>${badge(n?n.label:'Review selection',n?n.kind:'wait')}<span class="ws-arrow">›</span></button>`;}).join('')||empty('Your builder will prepare your selections here.')}</div></section><section class="ws-section"><div class="ws-section-head"><h2>Recent progress</h2>${button('All updates',"clientGo('progress')")}</div>${W.activity(p)}</section></div><aside><section class="ws-section"><div class="ws-section-head"><h2>Coming up</h2></div><div class="ws-panel">${W.schedule(p)}</div></section><div class="ws-panel ws-note"><div class="ws-eyebrow">Your build brief</div><h3>What matters to you?</h3><p>${e((p.buildBrief||{}).priorities||'How you want to live. What you love. What needs to last.')}</p>${button('Shape your brief',`SitePlumbWorkspace.brief(${js(p.id)})`)}</div><div class="ws-facts"><div><small>Selections</small><strong>${(p.selections||[]).length} recorded</strong></div><div><small>Net changes</small><strong>${e(invUsd(billingSummary(p).net))}</strong></div><div><small>Next visit</small><strong>${e(date(next&&next.start))}</strong></div></div></aside></div></div>`;
 };
 W.crewHome=p=>{const t=subTradeFor(p),ready=packetReady(p,t.id),n=W.next(p,t.id);return `<div class="workspace"><div class="ws-heading"><div><div class="ws-eyebrow">${e(t.label)} · Your work</div><h1>${e(p.street||p.name)}</h1></div></div><section class="ws-feature"><div><div class="ws-eyebrow">${ready?'Current instructions':'Installation on hold'}</div><h2>${ready?'Know exactly what goes in.':'Wait for approved instructions.'}</h2><p>${ready?'The homeowner and builder have both signed the current instructions. Review your packet before starting.':'Do not install. Both current approvals are required before this work can begin.'}</p><div class="ws-actions">${button('Your packet',`SitePlumbWorkspace.packet(${js(p.id)},${js(t.id)})`,true)}</div></div>${glance(p)}</section><div class="ws-grid"><section class="ws-section"><div class="ws-section-head"><h2>Your scope</h2>${badge(n.label,n.kind)}</div><div class="ws-panel">${tradeSelections(p,t.id).map(s=>`<button class="ws-row" onclick="SitePlumbWorkspace.packet(${js(p.id)},${js(t.id)})"><span class="ws-row-main"><strong>${e(s.item)}</strong><small>${e(s.room)}${s.spec&&s.spec.finish?' · '+e(s.spec.finish):''}</small></span><span class="ws-arrow">›</span></button>`).join('')}</div><div class="ws-actions">${button('Field notes',`subCapture(${js(p.id)})`)}${button('Documents',"subGo('docs')")}</div></section><aside><section class="ws-section"><div class="ws-section-head"><h2>Your dates</h2></div><div class="ws-panel">${W.schedule(p)}</div></section>${W.lifecycleHTML(p,t.id)}</aside></div></div>`;};
 W.decision=(id,t)=>{
   const p=project(id);if(!p)return;Data.setActive(p.id);const n=W.next(p,t),sels=tradeSelections(p,t),sign=packetSignoff(p,t),b=(p.bookings||[]).find(b=>b.trade===t&&b.status!=='declined');
   showInfo('Decision brief',`<div class="workspace"><div class="ws-eyebrow">${e(p.street)} · ${e(specLabel(t))}</div><h2>Everything needed for the next decision.</h2><p>${e(n.detail)}</p><div class="ws-facts"><div><small>Next with</small><strong>${e(n.who)}</strong></div><div><small>Scheduled work</small><strong>${e(date(b&&b.start))}</strong></div><div><small>Selection changes</small><strong>${e(invUsd(sels.reduce((a,s)=>a+(Number(s.price)||0),0)))}</strong></div></div>${(p.buildBrief||{}).priorities?`<div class="ws-callout"><b>Homeowner priorities</b><br>${e(p.buildBrief.priorities)}</div>`:''}<div class="ws-readout">${sels.map(s=>`<div><dt>${e(s.item)}</dt><dd>${e(s.room)}</dd></div>`).join('')}<div><dt>Homeowner approval</dt><dd>${sign.homeowner?'Signed':'Pending'}</dd></div><div><dt>Builder approval</dt><dd>${sign.builder?'Signed':'Pending'}</dd></div></div>${packetChangesHTML(p,t)}<div class="ws-actions">${button('Open install packet',`SitePlumbWorkspace.packet(${js(id)},${js(t)})`,true)}${role()==='builder'?sels.map(s=>button('Install spec sheet',`closeInfo();openSpec(${js(s.id)})`)).join(''):''}</div><p class="ws-caption">Cost shown is the recorded selection change. Schedule effects still require builder review.</p>${W.lifecycleHTML(p,t)}</div>`);
 };
 W.brief=id=>{const p=project(id);if(!p)return;const b=p.buildBrief||{};W.briefContext=id;showInfo('Your build brief',`<div class="workspace"><div class="ws-eyebrow">${e(p.street||p.name)}</div><h2>A home shaped around your life.</h2><p>Keep the things that matter close to every decision. Technical choices stay with the appropriate expert.</p><div class="ws-form"><label>What matters most?<small>Comfort, the way you live, the feel of your home.</small><textarea id="wsPriorities" placeholder="A quiet retreat, easy upkeep, room for everyone…">${e(b.priorities||'')}</textarea></label><label>Look & feel<input id="wsLook" value="${e(b.look||'')}" placeholder="Materials, colours, and spaces you love"></label><label>Budget & tradeoffs<textarea id="wsTradeoffs" placeholder="Where would you invest more? What could stay simple?">${e(b.tradeoffs||'')}</textarea></label></div><div class="ws-actions">${button('Save build brief','SitePlumbWorkspace.saveBrief()',true)}</div><p class="ws-caption">Sample brief · saved on this device for the homeowner and builder.</p></div>`);};
 W.saveBrief=()=>{const p=project(W.briefContext);if(!p||!['builder','client'].includes(role())||appMode()!=='demo')return toast('This brief is available in the sample workspace.');p.buildBrief={priorities:document.getElementById('wsPriorities').value.trim().slice(0,3000),look:document.getElementById('wsLook').value.trim().slice(0,1000),tradeoffs:document.getElementById('wsTradeoffs').value.trim().slice(0,3000),by:state.session.name,at:Date.now()};persist();closeInfo();W.refresh();toast('Build brief saved');};
 // Revision-bound demo records. The complete canonical approval key, rather
 // than a label or short hash, determines whether any record is current.
 W.reviewContext=null;
 W.lifecycleHTML=(p,t)=>{
   if(appMode()!=='demo'||window.PlumbStagingConfig)return '';
   const r=W.currentRecord(p,t),ready=packetReady(p,t),old=(p.workspaceRecords||[]).filter(r=>r.trade===t&&r.key!==packetApprovalKey(p,t));
   let h='<div class="ws-lifecycle workspace"><div class="ws-eyebrow">From instructions to finished work</div><h3>'+(!ready?'Do not install':r&&r.verified?'Installation verified':r&&r.installed?'Ready for independent review':r&&r.ack?'Instructions acknowledged':'Crew review comes next')+'</h3>';
   if(!ready)h+='<p>Current homeowner and builder approvals are required. Previous acknowledgments and installation records cannot authorize revised work.</p>';
   else if(r&&r.verified)h+='<p>Reviewed by '+e(r.verified.by)+'. The installation evidence matches these instructions.</p>';
   else if(role()==='subs')h+=r&&r.installed?'<p>Your installation evidence is recorded. The builder reviews it next.</p>':button(r&&r.ack?'Record installation':'Review & acknowledge',`SitePlumbWorkspace.workReview(${js(p.id)},${js(t)})`,true);
   else if(role()==='builder'&&r&&r.installed&&!r.verified)h+=button('Review installation',`SitePlumbWorkspace.workReview(${js(p.id)},${js(t)})`,true);
   else h+='<p>'+(r&&r.verified?'The builder reviewed the crew’s evidence for these instructions.':r&&r.ack?'The crew has acknowledged these exact instructions.':'The crew has not acknowledged these instructions yet.')+'</p>';
   if(r)h+='<p class="ws-caption">Record '+e(r.id)+(r.ack?' · acknowledged by '+e(r.ack.by):'')+'</p>';
   if(old.length)h+='<details class="ws-history"><summary>'+old.length+' superseded '+(old.length===1?'record':'records')+'</summary>'+old.map(x=>'<p class="ws-caption">'+e(x.id)+' · Superseded · retained for history</p>').join('')+'</details>';
   return h+'<p class="ws-caption">Sample workflow · saved on this device.</p></div>';
 };
 W.workReview=(id,t)=>{const p=project(id);if(!p)return;const r=W.currentRecord(p,t);W.reviewContext={id,t,key:packetApprovalKey(p,t)};const ready=packetReady(p,t),verify=role()==='builder'&&r&&r.installed;
   showInfo(verify?'Review installation':'Your current instructions',`<div class="workspace"><div class="ws-eyebrow">${e(p.street)} · ${e(specLabel(t))}</div><h2>${verify?'Does the work match the instructions?':r&&r.ack?'Record the completed work.':'Read it. Confirm it. Build it.'}</h2>${!ready?'<div class="ws-callout hold">Do not install. Current approvals are incomplete.</div>':''}${tradeSelections(p,t).map(s=>'<h3 style="margin-top:24px">'+e(s.item)+'</h3>'+specReadoutHTML(s)).join('')}${verify?`<div class="ws-proof"><b>${e(r.installed.by)} · ${e(date(r.installed.at))}</b><p>${e(r.installed.note)}</p>${r.installed.photo?`<img src="${e(r.installed.photo)}" alt="Crew installation evidence">`:''}</div><div class="ws-form"><label>Verification note<textarea id="wsVerifyNote" placeholder="What did you check against the instructions?"></textarea></label><label><input type="checkbox" id="wsVerifyCheck"> I independently checked the recorded work against these instructions.</label></div><div class="ws-actions">${button('Verify installation',"SitePlumbWorkspace.recordWork('verify')",true)}</div>`:ready&&role()==='subs'?r&&r.ack?`<div class="ws-form"><label>Installation evidence<small>Describe the work and the checks you completed.</small><textarea id="wsInstallNote" placeholder="Record what was installed, where, and what you checked."></textarea></label><label>Photo (optional)<input type="file" id="wsInstallPhoto" accept="image/jpeg,image/png,image/webp"></label></div><div class="ws-actions">${button('Save installation evidence',"SitePlumbWorkspace.recordWork('install')",true)}</div>`:`<p>Both roles have signed. Confirm you have reviewed the exact details above before you install.</p><div class="ws-actions">${button('Acknowledge instructions',"SitePlumbWorkspace.recordWork('ack')",true)}</div>`:''}<p class="ws-caption">Sample evidence is stored on this device. It is attached to this exact instruction revision.</p></div>`);
 };
 W.recordWork=async action=>{
   const c=W.reviewContext,p=c&&project(c.id);if(!p||appMode()!=='demo'||window.PlumbStagingConfig)return false;
   const valid=()=>c.key===packetApprovalKey(p,c.t)&&packetReady(p,c.t);
   if(!valid()){toast('Instructions changed or approval was withdrawn. Review the current packet.');return false;}
   const sess=state.session||{},isCrew=sess.role==='subs'&&(p.subs||[]).some(s=>s.name===sess.name&&s.specialty===c.t),isBuilder=sess.role==='builder';
   let r=W.currentRecord(p,c.t);
   if(action==='ack'){
     if(!isCrew)return false;if(r&&r.ack)return true;
     if(!r){p.workspaceRecords=p.workspaceRecords||[];r={id:'WR-'+(p.workspaceRecords.length+1),trade:c.t,key:c.key,instructions:copy(tradeSelections(p,c.t).map(selectionInstruction)),approvals:copy(packetSignoff(p,c.t)),createdAt:Date.now()};p.workspaceRecords.push(r);}
     r.ack={at:Date.now(),by:sess.name,actor:sess.auth&&sess.auth.uid||sess.name};
   }else if(action==='install'){
     if(!isCrew||!r||!r.ack||r.installed)return false;
     if(!(p.subs||[]).some(s=>s.name===sess.name&&s.specialty===c.t&&s.cleared)){toast('Wait for the builder to mark the site ready.');return false;}
     const note=(document.getElementById('wsInstallNote')||{}).value||'';if(note.trim().length<12){toast('Add an installation note describing the work and checks.');return false;}
     const file=(document.getElementById('wsInstallPhoto')||{}).files?.[0];let photo=null;
     if(file){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>1500000){toast('Choose a JPG, PNG, or WebP photo under 1.5 MB.');return false;}photo=await new Promise((resolve,reject)=>{const f=new FileReader();f.onload=()=>resolve(f.result);f.onerror=reject;f.readAsDataURL(file);}).catch(()=>null);if(!photo){toast('The photo could not be read. Your evidence has not been saved.');return false;}}
     if(!valid()||state.session!==sess){toast('The packet or signed-in role changed. Review it again.');return false;}
     r.installed={at:Date.now(),by:sess.name,actor:sess.auth&&sess.auth.uid||sess.name,note:note.trim().slice(0,5000),photo};
   }else if(action==='verify'){
     if(!isBuilder||!r||!r.installed||r.verified||r.installed.actor===(sess.auth&&sess.auth.uid||sess.name))return false;
     const note=(document.getElementById('wsVerifyNote')||{}).value||'';if(!document.getElementById('wsVerifyCheck')?.checked||note.trim().length<12){toast('Add your verification note and confirm the independent check.');return false;}
     r.verified={at:Date.now(),by:sess.name,actor:sess.auth&&sess.auth.uid||sess.name,note:note.trim().slice(0,5000)};
   }else return false;
   persist();closeInfo();W.refresh();toast({ack:'Instructions acknowledged',install:'Installation evidence saved',verify:'Installation verified'}[action]);return true;
 };
 W.refresh=()=>{if(role()==='client')renderClient();else if(role()==='subs')renderSubView();else{renderOverview();renderSiteSummary();} };
 const today=renderToday;renderToday=function(){today.apply(this,arguments);W.builderHome();};
 const overview=renderOverview;renderOverview=function(){overview.apply(this,arguments);W.builderHome();};
 const client=renderClient;renderClient=function(){client.apply(this,arguments);const p=clientProj();if(!p)return;document.getElementById('clWho').textContent='Homeowner';const body=document.getElementById('clBody');if(clientTab==='home')body.innerHTML=W.homeownerHome(p);else{if(clientTab==='specs'){const ledger=body.querySelector('.sel-ledger');if(ledger){const heading=ledger.previousElementSibling;if(heading&&heading.classList.contains('sec'))heading.remove();const details=document.createElement('details');details.className='ws-history';details.innerHTML='<summary>Costs & payments · '+e(invUsd(billingSummary(p).net))+' net change</summary>';details.appendChild(ledger);body.appendChild(details);}}body.innerHTML='<div class="workspace ws-client-body">'+W.nav(p,'client',clientTab)+'<div class="ws-heading"><div><div class="ws-eyebrow">'+e(p.street)+'</div><h1>'+({specs:'Your selections',progress:'Your home, in progress',docs:'Project documents'}[clientTab]||'Your home')+'</h1></div></div>'+body.innerHTML+'</div>';}};
 const crew=renderSubView;renderSubView=function(){crew.apply(this,arguments);const projs=subProjects();if(!subSel&&projs.length===1){subSel=projs[0].id;subTab='todo';}const p=projs.find(p=>String(p.id)===String(subSel));if(p&&subTab==='todo')document.getElementById('svBody').innerHTML=W.crewHome(p);};
 const summary=renderSiteSummary;renderSiteSummary=function(){summary.apply(this,arguments);const p=P(),el=document.getElementById('siteSummary');if(!p||!el)return;el.innerHTML='<div class="workspace ws-context"><div class="ws-eyebrow">House workspace</div><h2>'+e(p.street||p.name)+'</h2>'+W.nav(p,'builder','log')+'<div class="ws-actions">'+W.trades(p).map(t=>button(specLabel(t)+' install packet',`SitePlumbWorkspace.decision(${js(p.id)},${js(t)})`,true)).join('')+button('Build brief',`SitePlumbWorkspace.brief(${js(p.id)})`)+'</div></div>';};
 const originalSaveSpec=saveSpec;saveSpec=function(){const result=originalSaveSpec.apply(this,arguments);W.refresh();return result;};
 const packet=packetHTML;packetHTML=function(p,t){return packet.apply(this,arguments)+W.lifecycleHTML(p,t);};
 const selections=renderSelections;renderSelections=function(){selections.apply(this,arguments);const s=document.getElementById('selInstr');if(s)s.insertAdjacentHTML('afterbegin','<div class="workspace ws-selection-tools"><h2>Make every detail clear.</h2></div>');};
 document.documentElement.dataset.workspaceVersion='2026-09-10';
})();
